log:
    pm2: false
    appenders:
        stdout:
            type: "stdout"
    categories:
        default:
            appenders: [ "stdout" ]
            level: 'ALL'
        master:
            appenders: [ "stdout" ]
            level: "ALL"
        main:
            appenders: [ "stdout" ]
            level: "ALL"
        polling:
            appenders: [ "stdout" ]
            level: "ALL"

ipc:
    master:
        sock: dph.sock
    main:
        file: main
    polling:
        file: polling

supportedStandard:
    - "USD"

supportedCoin:
    - "BTC"

supportedExchange:
    - "bitfinex"
    - "binance"

exchanges:
    bitfinex:
        fees:
            taker: 0.001
            maker: 0.002
        apiKey: ''
        apiSecret: ''
        USDSymbols: 
            BTC : 'BTC/USD'
            LTC : 'LTC/USD'
            ETH : 'ETH/USD'
    binance:
        fees:
            taker: 0.001
            maker: 0.001
        apiKey: ''
        apiSecret : ''
        USDSymbols:
            BTC : 'BTC/USDT'

database:
    host: ''
    username: ''
    password: ''
    port: ''
    database: ''