log:
    pm2: false
    appenders:
        stdout:
            type: "stdout"
    categories:
        default:
            appenders: [ "stdout" ]
            level: 'ALL'
        master:
            appenders: [ "stdout" ]
            level: "ALL"
        main:
            appenders: [ "stdout" ]
            level: "ALL"
        polling:
            appenders: [ "stdout" ]
            level: "ALL"

ipc:
    master:
        sock: dph.sock
    main:
        file: main
    polling:
        file: polling

supportedStandard:
    - "USD"
    - "BTC"

supportedCoin:
    - "ETH"

supportedExchange:
    - "bitfinex"
    - "binance"
    - "zb"
    - "bittrex"
    - "bitstamp"
    - "huobipro"

exchanges:
    bitfinex:
        fees:
            buy: 0.002
            sell: 0.002
        apiKey: ''
        apiSecret: ''
        USDSymbols: 
            BTC : 'BTC/USD'
            LTC : 'LTC/USD'
            ETH : 'ETH/USD'
        BTCSymbols:
            ETH : 'ETH/BTC'
    binance:
        fees:
            buy: 0.001
            sell: 0.001
        apiKey: ''
        apiSecret : ''
        USDSymbols:
            BTC : 'BTC/USDT'
        BTCSymbols:
            ETH : 'ETH/BTC'
    zb:
        fees:
            buy: 0.002
            sell: 0.002
        USDSymbols:
            BTC: 'BTC/USDT'
        BTCSymbols:
            ETH : 'ETH/BTC'
    okex:
        fees:
            buy: 0.002
            sell: 0.002
        USDSymbols:
            BTC: 'BTC/USDT'
        BTCSymbols:
            ETH : 'ETH/BTC'
    bittrex:
        fees:
            buy: 0.002
            sell: 0.002
        USDSymbols:
            BTC: 'BTC/USDT'
        BTCSymbols:
            ETH : 'ETH/BTC'
    bitstamp:
        fees:
            buy: 0.002
            sell: 0.002
        USDSymbols:
            BTC: 'BTC/USD'
        BTCSymbols:
            ETH : 'ETH/BTC'
    huobipro:
        fees:
            buy: 0.002
            sell: 0.002
        USDSymbols:
            BTC: 'BTC/USDT'
        BTCSymbols:
            ETH : 'ETH/BTC'

strategyConfig:
    TH:
        thBuffer: 0.5

database:
    host: ''
    username: ''
    password: ''
    port: ''
    database: ''